import { IUser } from "@/models/admin.model";
import { IProduct } from "@/models/store.model";

export const API_URL = import.meta.env.VITE_BACKEND_API_URL_ENDPOINT;

export const store_products: IProduct[] = [
  {
    product_id: "P001",
    product_name: "Wireless Earbuds",
    product_img: "/wireless airpods.jpg",
    product_description:
      "High-quality wireless earbuds with noise cancellation.",
    category: ["Electronics"],
    price: 59.99,
    currency: "USD",
    sold: 120,
    discount: 10,
    date_created: "2024-01-15",
    created_by: "JohnDoe",
    other_details: {
      color: "White",
      battery: 20,
    },
  },
  {
    product_id: "P002",
    product_name: "Gaming Laptop",
    product_img: "/gaming laptop.jpg",
    product_description: "Powerful laptop for gaming with RGB keyboard.",
    category: ["Computers"],
    price: 1299.99,
    currency: "USD",
    sold: 45,
    discount: 20,
    date_created: "2024-02-20",
    created_by: "JaneSmith",
    other_details: {
      processor: "Intel Core i7",
      ram: 16,
      storage: 512,
    },
  },
  {
    product_id: "P003",
    product_name: "Smart Watch",
    product_img: "/Smart Watch.webp",
    product_description:
      "Water-resistant smartwatch with health tracking features.",
    category: ["Wearables"],
    price: 199.99,
    currency: "USD",
    sold: 350,
    discount: 15,
    date_created: "2024-03-01",
    created_by: "EmilyBrown",
    other_details: {
      water_resistant: true,
      health_tracking: true,
    },
  },
  {
    product_id: "P004",
    product_name: "Electric Toothbrush",
    product_img: "/Electric Toothbrush.jpg",
    product_description:
      "Rechargeable toothbrush with multiple cleaning modes.",
    category: ["Personal Care"],
    price: 49.99,
    currency: "USD",
    sold: 230,
    discount: 5,
    date_created: "2024-03-15",
    created_by: "ChrisJohnson",
    other_details: {
      cleaning_modes: 3,
      rechargeable: true,
    },
  },
  {
    product_id: "P005",
    product_name: "4K TV",
    product_img: "/4K TV.webp",
    product_description: "55-inch smart 4K Ultra HD TV with HDR support.",
    category: ["Home Entertainment"],
    price: 599.99,
    currency: "USD",
    sold: 110,
    discount: 10,
    date_created: "2024-04-05",
    created_by: "AlexLee",
    other_details: {
      screen_size: 55,
      hdr_support: true,
    },
  },
  {
    product_id: "P006",
    product_name: "Portable Bluetooth Speaker",
    product_img: "/Portable Bluetooth Speaker.jpg",
    product_description: "Waterproof portable speaker with deep bass.",
    category: ["Audio"],
    price: 39.99,
    currency: "USD",
    sold: 275,
    discount: 0,
    date_created: "2024-04-10",
    created_by: "SophiaDavis",
    other_details: {
      waterproof: true,
      bass: "deep",
    },
  },
  {
    product_id: "P007",
    product_name: "Digital Camera",
    product_img: "/Digital Camera.jpg",
    product_description: "Compact digital camera with 20x zoom.",
    category: ["Photography"],
    price: 349.99,
    currency: "USD",
    sold: 60,
    discount: 0,
    date_created: "2024-04-22",
    created_by: "LiamMartinez",
    other_details: {
      zoom: "20x",
      compact: true,
    },
  },
  {
    product_id: "P008",
    product_name: "Smartphone Tripod",
    product_img: "/Smartphone Tripod.jpg",
    product_description: "Lightweight and adjustable tripod for smartphones.",
    category: ["Photography"],
    price: 24.99,
    currency: "USD",
    sold: 410,
    discount: 0,
    date_created: "2024-05-01",
    created_by: "OliviaGarcia",
    other_details: {
      adjustable: true,
      lightweight: true,
    },
  },
  {
    product_id: "P009",
    product_name: "Electric Kettle",
    product_img: "/Electric Kettle.jpg",
    product_description: "Stainless steel kettle with rapid boiling feature.",
    category: ["Kitchen Appliances"],
    price: 29.99,
    currency: "USD",
    sold: 185,
    discount: 5,
    date_created: "2024-05-10",
    created_by: "MasonWilson",
    other_details: {
      material: "stainless steel",
      rapid_boiling: true,
    },
  },
  {
    product_id: "P010",
    product_name: "Desk Lamp",
    product_img: "/Desk Lamp.jpg",
    product_description:
      "LED desk lamp with adjustable brightness and USB port.",
    category: ["Home Decor"],
    price: 19.99,
    currency: "USD",
    sold: 350,
    discount: 10,
    date_created: "2024-05-20",
    created_by: "EmmaClark",
    other_details: {
      led: true,
      usb_port: true,
    },
  },
  {
    product_id: "P011",
    product_name: "Yoga Mat",
    product_img: "/Yoga Mat.webp",
    product_description: "Non-slip yoga mat with excellent cushioning.",
    category: ["Fitness"],
    price: 14.99,
    currency: "USD",
    sold: 560,
    discount: 0,
    date_created: "2024-06-01",
    created_by: "AidenWhite",
    other_details: {
      non_slip: true,
      cushioning: "excellent",
    },
  },
  {
    product_id: "P012",
    product_name: "Air Purifier",
    product_img: "/Air Purifier.jpg",
    product_description: "HEPA filter air purifier for home use.",
    category: ["Home Appliances"],
    price: 129.99,
    currency: "USD",
    sold: 85,
    discount: 0,
    date_created: "2024-06-12",
    created_by: "EllaThomas",
    other_details: {
      filter_type: "HEPA",
      usage: "home",
    },
  },
  {
    product_id: "P013",
    product_name: "Coffee Maker",
    product_img: "/Coffee Maker.jpg",
    product_description: "Single-serve coffee maker with fast brew technology.",
    category: ["Kitchen Appliances"],
    price: 89.99,
    currency: "USD",
    sold: 140,
    discount: 15,
    date_created: "2024-06-25",
    created_by: "JacobRobinson",
    other_details: {
      servings: "single",
      brew_speed: "fast",
    },
  },
  {
    product_id: "P014",
    product_name: "Tablet",
    product_img: "/Tablet.jpg",
    product_description: "10-inch tablet with 128GB storage and HD display.",
    category: ["Electronics"],
    price: 249.99,
    currency: "USD",
    sold: 95,
    discount: 30,
    date_created: "2024-07-05",
    created_by: "MiaWalker",
    other_details: {
      storage: "128GB",
      display: "HD",
      screen_size: 10,
    },
  },
  {
    product_id: "P015",
    product_name: "Smart Thermostat",
    product_img: "/Smart Thermostat.jpg",
    product_description: "Smart thermostat with voice control compatibility.",
    category: ["Home Automation"],
    price: 179.99,
    currency: "USD",
    sold: 70,
    discount: 0,
    date_created: "2024-07-10",
    created_by: "JamesAllen",
    other_details: {
      voice_control: true,
      energy_saving: true,
    },
  },
];

//delete this later when categories API fetching is established
export const categories = [
  "Mobile",
  "Cosmetics",
  "Watches",
  "Furniture",
  "Photography",
  "Kitchen Appliance",
  "Home Decor",
  "Fitness",
  "Home Appliance",
  "Electronics",
  "Home Automation",
];

export const services = [
  "About Us",
  "Terms & Conditions",
  "Contact Us",
  "FAQs",
  "Privacy Policy",
  "E-waste Policy",
  "Cancellation & Return Policy",
];

export const user = {
  user_id: "5177192a-997f-407f-85e8-d32b95e0ff8e",
  first_name: "Joel",
  last_name: "Malupiton",
  contact_number: "09232321231",
  address: "96 Etivac St, Sampaloc Cavite, 1191, Philippines",
  date_created: "2024-11-11T08:56:05.937",
  username: "boss!?ikawnanamanyan",
  access_level: "user",
  user_img: null,
  position: null,
  department: null,
  branch: null,
  group_tag: "group2-malakas",
};

export const usersList: IUser[] = [
  {
    user_id: "5177192a-997f-407f-85e8-d32b95e0ff8e",
    first_name: "Joel",
    last_name: "Malupiton",
    contact_number: "09232321231",
    address: "96 Etivac St, Sampaloc Cavite, 1191, Philippines",
    date_created: "2024-11-11T08:56:05.937",
    username: "boss!?ikawnanamanyan",
    access_level: "user",
    user_img: null,
    position: null,
    department: null,
    branch: null,
    group_tag: "group2-malakas",
  },
];

export const categoryList = [
  {
    category_id: "C001",
    category_name: "Electronics",
    category_img: "https://example.com/images/electronics.jpg",
    date_created: "2024-01-05",
    created_by: "JohnDoe",
  },
  {
    category_id: "C002",
    category_name: "Computers",
    category_img: "https://example.com/images/computers.jpg",
    date_created: "2024-01-15",
    created_by: "JaneSmith",
  },
  {
    category_id: "C003",
    category_name: "Wearables",
    category_img: "https://example.com/images/wearables.jpg",
    date_created: "2024-02-01",
    created_by: "EmilyBrown",
  },
  {
    category_id: "C004",
    category_name: "Personal Care",
    category_img: "https://example.com/images/personal-care.jpg",
    date_created: "2024-02-20",
    created_by: "ChrisJohnson",
  },
  {
    category_id: "C005",
    category_name: "Home Entertainment",
    category_img: "https://example.com/images/home-entertainment.jpg",
    date_created: "2024-03-10",
    created_by: "AlexLee",
  },
  {
    category_id: "C006",
    category_name: "Audio",
    category_img: "https://example.com/images/audio.jpg",
    date_created: "2024-03-25",
    created_by: "SophiaDavis",
  },
  {
    category_id: "C007",
    category_name: "Photography",
    category_img: "https://example.com/images/photography.jpg",
    date_created: "2024-04-05",
    created_by: "LiamMartinez",
  },
  {
    category_id: "C008",
    category_name: "Kitchen Appliances",
    category_img: "https://example.com/images/kitchen-appliances.jpg",
    date_created: "2024-04-20",
    created_by: "OliviaGarcia",
  },
  {
    category_id: "C009",
    category_name: "Home Decor",
    category_img: "https://example.com/images/home-decor.jpg",
    date_created: "2024-05-01",
    created_by: "MasonWilson",
  },
  {
    category_id: "C010",
    category_name: "Fitness",
    category_img: "https://example.com/images/fitness.jpg",
    date_created: "2024-05-15",
    created_by: "EmmaClark",
  },
];
