
export const ROUTES = {
  BASE: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  ACCESS_DENIED: "/access_denied",
  TEST: "/test",
  NOT_FOUND: "*",
  ADMIN: {
    BASE: "/admin",
    DASHBOARD: "/admin",
    PRODUCT: "/admin/products",
    CATEGORY: "/admin/category",
    USERS: "/admin/users",
    TRANSACTIONS: "/admin/transactions",
  },
  STORE: {
    HOME: "/store",
    PRODUCTS: "/store/all-products",
    CATEGORY: "/store/category",
    CART: "/store/cart",
    ABOUT: "/about",
    CONTACT_US: "/contact-us",
    PROFILE: "/store/profile",
    PROFILE_SETTINGS: "/store/profile/settings",
    CHECKOUT: "/store/checkout",
    CHECKOUT_SUCCESS: "/store/checkout/success",
  },
};
